### ISSUE TITLE
Extend 'ShellWithTextIsAvailable' condition (matcher)

### ISSUE THREAD

**Issue by tsedmik** [jboss-reddeer/reddeer#1000]
Add ability to use _ShellWithTextIsAvailable_ wait condition with matcher not only exact title name.

**Comment by mlabuda** [comment]
I would suggest to create different condition for this. Bcs ShellWithTextIsAvailable describe shell with specific text, not matcher. New wait condition could be called ShellMatchingMatcherIsAvailable and it would be precisely what it describes.

**Comment by mlabuda** [comment]
Well. I've just noticed we already have such condition. Please use condition ShellMatchingMatcherIsAvailable from org.jboss.reddeer.core package.
