### ISSUE TITLE
Update doc for #1057

### ISSUE THREAD

**Issue by rawagner** [jboss-reddeer/reddeer#1058]

**Comment by rhopp** [comment]
I've edited https://github.com/jboss-reddeer/reddeer/wiki/Menu 

ToolBarMenu is no longer there. Instead of it, ViewMenu and ToolItemMenu were added.

**Comment by mlabuda** [comment]
Please fix following:
* add screenshot for shell menu
* change screenshot to show real content of view menu, not view tool item next to menu (expanded down-arrow)
* add screenshot for view menu example (working sets inside project explorer)

**Comment by rhopp** [comment]
Done.
P.S.: I didn't add screenshot for shell menu because I think it is not needed. Instead of this I've added text description.

**Comment by mlabuda** [comment]
Ok, now it's OK.
