### ISSUE TITLE
Remove ExplorerItemPropertyPage and leave ProjectProjertyPage

### ISSUE THREAD

**Issue by mlabuda** [jboss-reddeer/reddeer#1063]
Changes introduced in  #1052 provide ExplorerItemPropertyPage. I think such property page is not good to have because ExplorerItem as an abstraction of any item in *Explorer does not have to have context menu - explorer items in general can be without it. This could case exceptions on calling property pages on such items.

What do you think @ljelinkova ?

**Comment by ljelinkova** [comment]
After team discussion we shall keep the ExplorerItemPropertyPage.
