### ISSUE TITLE
Document RedDeer User profile feature

### ISSUE THREAD

**Issue by vpakan** [jboss-reddeer/reddeer#1075]

**Comment by vpakan** [comment]
https://github.com/jboss-reddeer/reddeer/wiki/User-Profile

**Comment by jpeterka** [comment]
* would be good to add additional information where it should be located on OSX and Windows and (or) if there are any differences. Not sure about it but "dot" files on Windows might be hidden by default IMHO
* and general file description like variable=value could be added after third paragraph
* I guess some some "a,an,the" are missing but I'm not an expert ;-)

**Comment by vpakan** [comment]
* it written there that it is in user home directory I think it's clear enough
* it's written there that file is standard java properties file this file description is widely use in many docs
* my English is not sufficient to decide where are missing "a,an,.the"

**Comment by jpeterka** [comment]
Ok, we don't need to go into that much detail if think it's obvious.

Just noticed one more thing 
* "...just create file simple properties file called .reddeer"  sentence doesn't sounds good to me.  First "file" should be removed or some commas should be added.

**Comment by vpakan** [comment]
Thanks for catching this typo now it's fixed
