### ISSUE TITLE
Revise requirements documentation

### ISSUE THREAD

**Issue by mlabuda** [jboss-reddeer/reddeer#1076]
https://github.com/jboss-reddeer/reddeer/wiki/Requirements

**Comment by ljelinkova** [comment]
- test revision is finished
- TODO: snippets

**Comment by mlabuda** [comment]
Wiki doc page looks fine.

**Comment by ljelinkova** [comment]
The snippets are updated too

**Comment by mlabuda** [comment]
review. It's ok.
