### ISSUE TITLE
ljelinko_Doc on how to update snippets

### ISSUE THREAD

**Issue by mlabuda** [jboss-reddeer/reddeer#1089]

**Comment by mlabuda** [comment]
Related to #1077.

**Comment by mlabuda** [comment]
https://github.com/jboss-reddeer/reddeer/wiki/How-to-update-snippets-and-examples

**Comment by ljelinkova** [comment]
- I'd add information about how the wiki page should look like (that it should contain ```java or ```xml with ending ``` on a separate line
- I think this should go to the Developers guide not to the User guide

**Comment by mlabuda** [comment]
done, referenced added to contributor's guide, but also left in user guide (we do even have there a document on how to build RedDeer)

**Comment by ljelinkova** [comment]
Reviewed, closing the issue.
