### ISSUE TITLE
vpakan_Document How to import RedDeer sources from git

### ISSUE THREAD

**Issue by vpakan** [jboss-reddeer/reddeer#1097]
1. clone repo
2. o.j.r.junit,test now needs Mockito and Hamcrest therefore features org.hamcrest (Hamcrest Library of Matchers) and org.mockito (Mockito Mock Library for Java) have to be installed. They could be found on appropriate Eclipse Orbit update site http://download.eclipse.org/tools/orbit/downloads/
3. import as maven project

**Comment by mlabuda** [comment]
See https://github.com/jboss-reddeer/reddeer/wiki/Developer-guide

**Comment by mlabuda** [comment]
Fixed some issues.

**Comment by vpakan** [comment]
Looks fine to me
