### ISSUE TITLE
Cannot install RedDeer master on Mars

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1138]
Step: Have clean Eclipse Mars JEE installation
Step: Try to install RedDeer from master site: http://download.jboss.org/jbosstools/mars/snapshots/builds/reddeer_master/

**Comment by mmalina** [comment]
@jpeterka you told me personally that this is different than #1139 - that you also see GEF missing. But I tried twice and I can't see any other missing dep other than org.mockito. So I'm assigning this back to you to try again. Once I added Eclipse Orbit update site, the dependencies were fine.

**Comment by jpeterka** [comment]
This was caused by https://bugs.eclipse.org/bugs/show_bug.cgi?id=470900 , after applying workaround it works, closing.
