### ISSUE TITLE
Master matrix job is not did not finish

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1142]
see http://machydra.brq.redhat.com:8080/view/RedDeer/job/RedDeer_master_matrix/

**Comment by mmalina** [comment]
It did not finish, because it was set to run on fenix and fenix is not available (I installed Fedora 22 there and since then I cannot boot the machine and I asked online for help, but got no response. I will try to make it work again today.) I switched fenix for rewok for now.
