### ISSUE TITLE
Document Parser Log usage

### ISSUE THREAD

**Issue by vpakan** [jboss-reddeer/reddeer#1147]

**Comment by vpakan** [comment]
Please review https://github.com/jboss-reddeer/reddeer/wiki/RedDeer-Log-Parser

**Comment by jpeterka** [comment]
Please change "display lines before - specify how many lines from original log preceding line will be included in parsed log will be also included in parsed log"

to 

"display lines before - number of lines preceding a matching line of the original log displayed in the parsed log"

Same for after

**Comment by vpakan** [comment]
Fixed therefore closing
