### ISSUE TITLE
Release RedDeer 0.8

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1180]
Steps:
Change to 0.8 
Update and release maven artefact
Tag 0.8
Build stable update site
Update JBT beta2 to 0.8 stable
Change to 1.0-snapshot

Notes from previous release : https://github.com/jboss-reddeer/reddeer/issues/973

**Comment by mmalina** [comment]
0.8.0 release PR is here: #1181

**Comment by jpeterka** [comment]
0.8.0 pushed to master and tagged

**Comment by mmalina** [comment]
RedDeer 0.8.0 is now available from this stable update site: http://download.jboss.org/jbosstools/updates/stable/mars/core/reddeer/0.8.0/

**Comment by jpeterka** [comment]
Installation test passed

**Comment by jpeterka** [comment]
Wiki updated, mail and tweet sent.

**Comment by mmalina** [comment]
Archetype is available here:
https://origin-repository.jboss.org/nexus/content/repositories/releases/org/jboss/reddeer/jboss-reddeer-archetype/0.8.0.Final/
Instructions on how to release it:
https://developer.jboss.org/wiki/WildflyExtrasRepository

**Comment by mmalina** [comment]
Note about archetype for next time: Don't forget to update version of archetype/pom.xml and also update update site for next release in the archetype code.

**Comment by mmalina** [comment]
Version updated to 1.0.0-SNAPSHOT: #1185

**Comment by jpeterka** [comment]
pushed to master

**Comment by mmalina** [comment]
Integration tests branch Beta2x will now point to 0.8.0 instead of master RedDeer repo: https://github.com/jbosstools/jbosstools-integration-tests/pull/1098
And master will use 0.8.0 as the stable repo: https://github.com/jbosstools/jbosstools-integration-tests/pull/1099

**Comment by mmalina** [comment]
Update site zip is attached to the release in GitHub: https://github.com/jboss-reddeer/reddeer/releases/tag/v0.8.0

**Comment by mmalina** [comment]
OK, so this issue can be closed. The PRs for integration tests are really independent on this.
