### ISSUE TITLE
Migrate RedDeer documentation from wiki to help plugin

### ISSUE THREAD

**Issue by mlabuda** [jboss-reddeer/reddeer#1219]
Each part consists of following steps:
- Create html pages for github wiki pages and place them into RedDeer Help plugin
- Add href to html pages into existing TOC (Table of Contents) located in org.jboss.reddeer.help/toc.xml
- When moving snippets, use just code block for java code. Currently we don't have mechanism to do this automatically and I am going to create such a feature later (Syntax highlight and some javascript...)
- use CSS, you can also extend an existing one locate in org.jboss.reddeer.help/doc/css/common.css
- please do not change hierarchy of pages in TOC

**Comment by mlabuda** [comment]
Subtasks:
#1220
#1221
#1222
#1223
#1224
#1225
#1226

**Comment by jpeterka** [comment]
@mlabuda can you update this? I assume you've mentioned we should use AsciiDoc format. Provide additional details if there are any specifics.

**Comment by mlabuda** [comment]
Closing. Decided to not migrate at the moment. Keep in .md format.
