### ISSUE TITLE
Update site title is "eclipse-orbit-update-site - ${update.site.description} Update Site"

### ISSUE THREAD

**Issue by nickboldt** [jboss-reddeer/reddeer#1249]
CI builds have incorrect title on the site.

http://download.jboss.org/jbosstools/mars/snapshots/builds/reddeer_master/latest/all/repo/

**Comment by nickboldt** [comment]
PR: https://github.com/jboss-reddeer/reddeer/pull/1250

**Comment by rawagner** [comment]
fixed in https://github.com/jboss-reddeer/reddeer/pull/1250
