### ISSUE TITLE
Document configuration of timeout factor

### ISSUE THREAD

**Issue by ljelinkova** [jboss-reddeer/reddeer#1259]
- create separate article
- add property to https://github.com/jboss-reddeer/reddeer/wiki/RedDeer-execution-parameters

**Comment by ljelinkova** [comment]
Updated documentation here:

https://github.com/jboss-reddeer/reddeer/wiki/Waits-and-timeouts

and here:

https://github.com/jboss-reddeer/reddeer/wiki/RedDeer-execution-parameters

**Comment by mlabuda** [comment]
It looks fine. Closing.
