### ISSUE TITLE
rev_User Guide - Howto run RedDeer tests in Jenkins environment

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#126]
Add a chapter about Howto run RedDeer tests in Jenkins environment  (https://github.com/jboss-reddeer/reddeer/wiki/User-Guide)

Please follow https://github.com/jboss-reddeer/reddeer/wiki/UserGuideTemplate for more information about User Guide

**Comment by jpeterka** [comment]
@ldimaggi , Len. What is the status here?

**Comment by ldimaggi** [comment]
In progress - I added text on March 24 - but there doesn't seem to be much to say. Can you review what is in the guide now?

**Comment by jpeterka** [comment]
Looks good I've just removed some duplicate information and added few links into direct documentation section.
