### ISSUE TITLE
Lots of failing tests on firebird

### ISSUE THREAD

**Issue by apodhrad** [jboss-reddeer/reddeer#1302]

**Comment by mmalina** [comment]
It seems that for some reason the screen lock was activated - perhaps after some update. Radim disabled it. But the system is still misbehaving. RedDeer tests are timing out on swt tests. Investigating.

**Comment by mmalina** [comment]
Firebird was updated to run Fedora 22 and should work correctly now. @apodhrad please let me know if you still see issues, thanks.

**Comment by apodhrad** [comment]
Thank you! No it is working (checked on Dec 7)
