### ISSUE TITLE
Update doc for exec parameters

### ISSUE THREAD

**Issue by apodhrad** [jboss-reddeer/reddeer#1305]
Update doc at https://github.com/jboss-reddeer/reddeer/wiki/RedDeer-execution-parameters
See #1234

**Comment by apodhrad** [comment]
Done. Please review the doc.

**Comment by ljelinkova** [comment]
The parameters are used throughout the documentation, e.g. https://github.com/jboss-reddeer/reddeer/wiki/JUnit-test-extensions

I think that the whole reddeer.wiki repo should be inspected for the occurrences and changed.

**Comment by mlabuda** [comment]
Fixed occurrence on all places. Closing.
