### ISSUE TITLE
Slow test execution on OSX slave

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1325]
http://machydra.brq.redhat.com:8080/job/RedDeer_master_matrix_report/514/artifact/reddeermastermatrixtestresults.html

This time: zamek

**Comment by mmalina** [comment]
It seems that zamek is now even slower than it used to be. On domek the test is finished in around 1 hr 50 min. On zamek, 140 min is not enough and then it times out. I was not able to find out the cause of this. As an immediate measure I removed the stable-mac label from zamek.

**Comment by jpeterka** [comment]
Strange, it seems we have two various issues here: 
1) tests are frozen during execution and timeouts (#1328)
2) tests are processing but very slow and timeouts

**Comment by mmalina** [comment]
OK, so this is a duplicate of long standing issue #1174 . Closing.

**Comment by mmalina** [comment]
I created an internal JIRA to reinstall zamek to see if that helps because I ran out of other ideas. Tracked in JBQA-12583 . Closing this issue.
