### ISSUE TITLE
Frozen jobs on OSX machine

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1328]
http://machydra.brq.redhat.com:8080/job/RedDeer_verification_matrix/jdk=sunjdk1.7,label=stable-mac/2418/consoleFull

**Comment by mmalina** [comment]
@jpeterka this is a known issue and the workaround in place is to have a script that connects to the mac slaves regularly via vnc. Unfortunately marvin died so the script was not running. I am now trying to experiment again to disable the sleep on domek, but I'm not sure if anything will help here.

**Comment by mmalina** [comment]
@jpeterka I tried to enable sleep and then disable it again on domek - some people suggested that the displayed settings in System Preferences could show incorrect state. It seems it helped. At least a build passed here: http://machydra.brq.redhat.com:8080/view/RedDeer/job/RedDeer_master/1025/

**Comment by mmalina** [comment]
For zamek, I will try to reinstall it to see if that helps. I created an internal JIRA for that (JBQA-12583) so I'm going to close this issue.
