### ISSUE TITLE
Release RedDeer 1.0.0

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#1334]
Steps:
Change to 1.0.0 
Update and release maven artifact
Tag 1.0.0
Build stable update site
Change to 1.1.0-snapshot

Notes from previous release : #1180 

Note: Branching for the future:
* master (will contain 1.1.0-snapshot)
* 1.0.x (for service release if needed)
* 2.x (API breaking new release attempt)

**Comment by mmalina** [comment]
PR for 1.0.0.Final release: https://github.com/jboss-reddeer/reddeer/pull/1335

**Comment by jpeterka** [comment]
PR pushed to master and tagged

**Comment by mmalina** [comment]
RedDeer 1.0.0 is now available from this stable update site:
http://download.jboss.org/jbosstools/updates/stable/mars/core/reddeer/1.0.0/

**Comment by mmalina** [comment]
Update site zip available here:
https://github.com/jboss-reddeer/reddeer/releases/tag/v1.0.0

**Comment by mmalina** [comment]
Archetype is available here:
https://origin-repository.jboss.org/nexus/content/repositories/releases/org/jboss/reddeer/jboss-reddeer-archetype/1.0.0.Final/
Instructions on how to release it:
https://developer.jboss.org/wiki/WildflyExtrasRepository

**Comment by mmalina** [comment]
Wiki updated by @jpeterka

**Comment by mmalina** [comment]
PR to update version to 1.1.0-SNAPSHOT: https://github.com/jboss-reddeer/reddeer/pull/1343

**Comment by mmalina** [comment]
I believe everything is done.
