### ISSUE TITLE
Provide an update site for delivering updates

### ISSUE THREAD

**Issue by apodhrad** [jboss-reddeer/reddeer#1345]
Currently we have
* http://download.jboss.org/jbosstools/updates/stable/mars/core/reddeer/0.8.0/
* http://download.jboss.org/jbosstools/updates/stable/mars/core/reddeer/1.0.0/

If we release for example 1.0.1 the there will be another update site for it. Then, each user must add this site to update the RedDeer. I suggest to create a composite site which always refer to the latest stable version so that users will use only one site
* http://download.jboss.org/jbosstools/updates/stable/mars/core/reddeer

**Comment by mmalina** [comment]
@apodhrad I just came across this issue and noticed that we already have what you're asking for:
http://download.jboss.org/jbosstools/updates/stable/mars/core/reddeer/
I'm not aware of us doing anything special to get it - it seems like it was done automatically by some of Nick's scripts. Is there anything else you'd like? If not, please resolve this issue.

**Comment by rawagner** [comment]
@apodhrad please verify

**Comment by rawagner** [comment]
@apodhrad please verify

**Comment by apodhrad** [comment]
I tried to install it and I got the following error
```
Cannot complete the install because of a conflicting dependency.
  Software being installed: RedDeer Eclipse Testing Source Feature 0.8.0.Final (org.jboss.reddeer.eclipse.feature.source.feature.group 0.8.0.Final)
  Software being installed: RedDeer Eclipse Testing Source Feature 1.0.2.Final (org.jboss.reddeer.eclipse.feature.source.feature.group 1.0.2.Final)
  Only one of the following can be installed at once: 
    RedDeer Eclipse Testing Source Feature 0.8.0.Final (org.jboss.reddeer.eclipse.feature.source.feature.jar 0.8.0.Final)
    RedDeer Eclipse Testing Source Feature 1.0.2.Final (org.jboss.reddeer.eclipse.feature.source.feature.jar 1.0.2.Final)
  Cannot satisfy dependency:
    From: RedDeer Eclipse Testing Source Feature 0.8.0.Final (org.jboss.reddeer.eclipse.feature.source.feature.group 0.8.0.Final)
    To: org.jboss.reddeer.eclipse.feature.source.feature.jar [0.8.0.Final]
  Cannot satisfy dependency:
    From: RedDeer Eclipse Testing Source Feature 1.0.2.Final (org.jboss.reddeer.eclipse.feature.source.feature.group 1.0.2.Final)
    To: org.jboss.reddeer.eclipse.feature.source.feature.jar [1.0.2.Final]
```

It seems that there are some conflicts between 0.8.0 and 1.0.2. I suggest to include only the latest version into composite files. @mmalina wdyt?

**Comment by apodhrad** [comment]
Currently, the composite files define
```
<children size="4">
  <child location="1.0.2/"/>
  <child location="1.0.1/"/>
  <child location="1.0.0/"/>
  <child location="0.8.0/"/>
</children>
```
Moreover, the installation takes much longer :(

**Comment by mmalina** [comment]
I asked Nick if there's anything we can do about this.
I agree that it would be best to only include the latest version. But note that in a way it's your fault that you want to install incompatible features from the aggregate update site - if you only choose features from RedDeer 1.0.2, then you can install them without a problem

**Comment by apodhrad** [comment]
The problem is that I just checked all categories but some of the categoris are available only in 0.8.0
![reddeer_catgories](https://cloud.githubusercontent.com/assets/2270674/17139076/497bd550-5343-11e6-8218-066c37284395.png)

**Comment by mmalina** [comment]
Yes, exactly. You should only check features of version 1.0.2 - unfortunately that's a side effect of combining all the update sites - features that were removed in later versions are still there on the update site - in the older versions. So simply checking everything will not work.
So we need the aggregate update site to only point to the latest version and this problem will disappear.

**Comment by nickboldt** [comment]
Had a bug in the jbosstools-cleanup.sh script, so it wasn't respecting the usual limit of 2 builds to include in the composite (thus was using all of them). 

https://github.com/jbosstools/jbosstools-build-ci/commit/0c351741db4ff5e2b0e5df854ad0bc73a02f95ff

Meanwhile, I've changed the rsync job so that if you're pushing to a /stable/ folder, you composite only 1 build; otherwise 2.

https://github.com/jbdevstudio/jbdevstudio-ci/commit/ff07e5824eec28b6c00bd922e21d4c48bf862e76#diff-e334fe82db3320cc312a1a700af38536R95

**Comment by mmalina** [comment]
awesome! thanks @nickboldt ! and I see you've already applied this to the repo somehow so it's including just the latest version now. so this issue can be closed.

**Comment by apodhrad** [comment]
Great! Now it works without any problem, Thx!
