### ISSUE TITLE
Update wiki to be up to date

### ISSUE THREAD

**Issue by mlabuda** [jboss-reddeer/reddeer#1378]
e.g. getting started pages contains deprecated labels and images

**Comment by jstefek** [comment]
please, don't forget to mention somewhere the property `-Dusage_reporting_enabled=false` (e.g. in Write-and-run-your-first-minimal-functional-test)

**Comment by rawagner** [comment]
That property is specific to JBoss Tools/JBDS and RedDeer is aimed at general Eclipse IDE testing thus this is not a proper place.

**Comment by mlabuda** [comment]
Updating will be part as part of migration. Closing this one.
