### ISSUE TITLE
Browser tests open the web browser instead of the browser in IDE

### ISSUE THREAD

**Issue by apodhrad** [jboss-reddeer/reddeer#1380]
Tests in error: 
  BrowserViewTest.openBrowser:34 » CoreLayer No matching widget found with Match...
  BrowserViewTest.openBrowser:34 » CoreLayer No matching widget found with Match...
  BrowserEditorTest.testEditor:60 » CoreLayer Unable to find editor matching spe...
  Timeout after: 60 s.: The following jobs are still running
	Refreshing server adapter list

Moreover, the tests then freeze

![reddeer_rewok](https://cloud.githubusercontent.com/assets/2270674/13957690/9d628f8c-f04d-11e5-8366-d39281197a3a.png)

**Comment by odockal** [comment]
Suppose to be resolved by https://issues.jboss.org/browse/JBQA-12905, closing.
