### ISSUE TITLE
Ensure that BrowserTest uses the internal Eclipse browser

### ISSUE THREAD

**Issue by apodhrad** [jboss-reddeer/reddeer#1394]

**Comment by apodhrad** [comment]
Possible solutions:
- set the browser in preferences
- https://lists.ubuntu.com/archives/ubuntu-in/2014-May/011512.html

**Comment by rawagner** [comment]
I've installed libwebkitgtk-1.0.0 and it fixed the problem. I havent tried the other option but i think that setting browser in preferences wouldnt work since choosing internal browser would be disabled because of missing library.
