### ISSUE TITLE
Wrong name in RedDeer update site

### ISSUE THREAD

**Issue by apodhrad** [jboss-reddeer/reddeer#1427]
http://download.jboss.org/jbosstools/updates/stable/mars/core/reddeer/compositeArtifacts.xml
http://download.jboss.org/jbosstools/updates/stable/mars/core/reddeer/compositeContent.xml

![reddeer_wrong_name](https://cloud.githubusercontent.com/assets/2270674/17143440/8ea79528-5353-11e6-815e-73acbb4c25fd.png)

**Comment by mmalina** [comment]
This does not look like a blocker to me.
I took a look but I'm not sure where this is defined. Probably in the org.jboss.tools.releng:jbosstools-releng-publish maven plugin. I will need to ask Nick.

**Comment by apodhrad** [comment]
You are right and I really don't know why I set it as a blocker...

**Comment by mmalina** [comment]
@nickboldt is there a way to configure this in the jenkins job or is this name hardcoded in the plugin?

**Comment by nickboldt** [comment]
This composite site is a generated one, using generic defaults. I don't think we have a way to pass in a custom name there.

http://download.jboss.org/jbosstools/mars/stable/updates/core/reddeer/compositeArtifacts.xml

But... I could remove the "JBoss Tools Builds" prefix there and just call the site "mars/stable/updates/core/reddeer/"

https://github.com/jbosstools/jbosstools-build-ci/blob/jbosstools-4.4.x/util/cleanup/jbosstools-cleanup.sh#L262 

If you'd like that change, please open a JIRA in JBIDE, component = build.

**Comment by mmalina** [comment]
@nickboldt , ok, thanks, here you go: https://issues.jboss.org/browse/JBIDE-22876

**Comment by mmalina** [comment]
Done, see here: http://download.jboss.org/jbosstools/neon/snapshots/builds/reddeer_master/compositeContent.xml
