### ISSUE TITLE
Add new condition class for - LabeledTextIsAvailable

### ISSUE THREAD

**Issue by ldimaggi** [jboss-reddeer/reddeer#1429]
Some tests written using Red Deer are experiencing intermittent failures due to timing issues related to new run configurations being created. A solution is to enable the tests to wait for the run configuration "Name:" labeled text to be available. 

This requires the creation of a new class:  org.jboss.reddeer.swt.condition.LabeledTextIsAvailable

**Comment by rawagner** [comment]
Len, you can use WidgetIsFound

`new WidgetIsFound<org.eclipse.swt.widgets.Text>(new ClassMatcher(org.eclipse.swt.widgets.Text.class), new WithLabelMatcher(label))`
