### ISSUE TITLE
Remove class WizardPage

### ISSUE THREAD

**Issue by apodhrad** [jboss-reddeer/reddeer#1447]
This class is completely useless but it cannot be removed in 1.x due to a backward compatibility. Let's remove it in RedDeer 2.0.

**Comment by mlabuda** [comment]
But we have to mark it as deprecated at least. Create a separate issue to mark the class deprecated and once we bump to 2.0. we remove it.

**Comment by apodhrad** [comment]
Good point! The issue created at #1447

**Comment by rawagner** [comment]
rejected
