### ISSUE TITLE
Reimplement SetOpenAssociatedPerspectiveExt so that it uses direct api

### ISSUE THREAD

**Issue by apodhrad** [jboss-reddeer/reddeer#1467]
Reimplement SetOpenAssociatedPerspectiveExt so that it uses direct api, e.g. sets the preferences via eclipse api. Currently, the logic opens the preference dialog which is not necessary.
The result will be faster and more stable tests.

**Comment by rawagner** [comment]
fixed in https://github.com/jboss-reddeer/reddeer/pull/1364
