### ISSUE TITLE
When AbstractEditor is active but not focused, should focus

### ISSUE THREAD

**Issue by odockal** [jboss-reddeer/reddeer#1469]
sometimes, it happens that TextEditor is active but not focused and work with editor fails on WaitTimeoutException when calling contentAssistant for example.

**Comment by rawagner** [comment]
can you attach stack trace ?

**Comment by odockal** [comment]
I played around a bit and found out that it seems like a problem from derived implementation of TextEditor class used in problematic jbosstools plugin. I will try to dig around more.

**Comment by odockal** [comment]
I made a [jira](https://issues.jboss.org/browse/JBIDE-23132) for this issue, probably it is from upstream.

**Comment by rawagner** [comment]
not a bug in RD then, closing
