### ISSUE TITLE
Create a new class to model the Maven->Errors/Warnings" preference page

### ISSUE THREAD

**Issue by ldimaggi** [jboss-reddeer/reddeer#1501]

**Comment by ldimaggi** [comment]
https://github.com/jboss-reddeer/reddeer/pull/1502

**Comment by mlabuda** [comment]
Len, next time please follow these steps https://github.com/jboss-reddeer/reddeer/wiki/Developer-guide#submitting-a-contribution

**Comment by rawagner** [comment]
closing, PR pushed to master
