### ISSUE TITLE
Create WidgetExist class

### ISSUE THREAD

**Issue by mlabuda** [jboss-reddeer/reddeer#1522]
Class should be similar to WidgetResolver on core layer but this one should work with RedDeer SWT widgets. It should have a method static boolean widgetExists(Class<? extends Widget> widgetClass, Matcher matcher), optionally static boolean widgetExists(Class<? extends Widget> widgetClass, String text). 

Purpose of this is to have a method to easily test existence of widges - e.g. user except open widget and want to assert that such a widget exists, then instead of try catch block with failure it would be assertTrue("Widget XYZ is not found ...", widgetExists(SomeWidget.class, matcher));

**Comment by rawagner** [comment]
we decided that existing condition - WidgetIsFound is sufficient
