### ISSUE TITLE
Decide on naming convention for Interface and default implementation

### ISSUE THREAD

**Issue by rawagner** [jboss-reddeer/reddeer#1549]
Currently we use this naming convention:
Interface is called Button
Default implementation is DefaultButton
other implementations are *Button (PushButton, CheckButton and so on)

Eclipse uses I-prefix for interface (IWorkspace)

The question is if we want to keep using the current naming convention, or start using I-prefix (interface would be IButton, default impl Button) or something else ?

@rhopp @mlabuda @apodhrad @odockal @mmalina @psrna @tsedmik

**Comment by psrna** [comment]
To be honest I like the eclipse naming convention more and with our long term plan moving reddeer under eclipse it makes sense to use their convention. But if we change the naming convention we will make the adoption of redder 2.0 harder for the user. It's 50:50 for me.

**Comment by mlabuda** [comment]
I am ok with Button for interface and DefaultButton for interface.

Reasoning: this would also apply for Project and DefaultProject and then JavaProject, MavenProject etc. Or respectively interface Server and impl. DefaultServer... We won't avoid some API changes and current approach with Default is familiar for many people and easy to use.

**Comment by apodhrad** [comment]
I don't like the I-prefix. I suggest to use a general name for an interface. Then, we can use the following convention
- Abstract<interface-name>
- Default<interface-name>
- <concrete-impl><interface-name>

We can also discuss the name for default implementations (Default, Basic, Base, Initial, Standard, etc.)

**Comment by rhopp** [comment]
I am for "natural" naming of interfaces and specific naming for implementations (as it is now). This means I'm against the "I" prefix.
Overall I'm pretty happy with the naming conventions we have in here ;-)

**Comment by apodhrad** [comment]
@rhopp the problem is with components such as Project or Server. Currently, there is a concrete implementation called Project, resp. Server but we want to divide the logic into interface, abstract class and impl class. For example:
- Server (interface)
- AbstractServer (abstract class)
- DefaultServer (concrete impl)

which IMHO is ok - we use such naming in swt widgets.

Another question is whether we will continue using the name *Default*.

**Comment by rhopp** [comment]
@apodhrad In cases you mentioned it's pretty straight forward: Server (interface), AbstractServer (abstract class), JBossServer, DefaultServer (GenericServer?), OpenShiftServer (implementation classes). For Project I would have to know the context, but this can be applied almost anywhere I think.

As for _Default_ prefix, I like it a lot better, than commonly used suffix _-Impl_ (ServerImpl - yuck! :confounded:)

**Comment by mlabuda** [comment]
We decided to go with ClassName for interface, AbstractClassName for abstract class and DefaultClassName for initial, basic, default... implementation.
