### ISSUE TITLE
Fix Graphiti plugin visiblity

### ISSUE THREAD

**Issue by mlabuda** [jboss-reddeer/reddeer#1557]
org.jboss.reddeer.graphiti (contains Graphiti exception) and org.jboss.reddeer.graphiti.lookup packages are not exported nor marked as internal. Please fix this.

**Comment by apodhrad** [comment]
Created a new PR at #1634 due to the following error

```
Error creating pull request: Unprocessable Entity (HTTP 422)
fork_collab Fork collab can't be granted by someone without permission
```
