### ISSUE TITLE
TextEditor.insertLine adds string null in case that actual editor does not have any delimiter

### ISSUE THREAD

**Issue by odockal** [jboss-reddeer/reddeer#1573]
For some editors, getLineDelimiter in insertLine method  (text + TextEditorHandler.getInstance().getDocument((ITextEditor)getEditorPart()).getLineDelimiter(line))
returns null and thus, text to insert is text+"null". Null should be checked and probably empty string returned instead.

**Comment by odockal** [comment]
This situation occurs when you are trying to insert text into line where is some content. For example, insertLine(edtior.getLineOfText("someText"), textToInsert);

**Comment by theJNOVAK** [comment]
Not reproduced when you are trying to insert text into line where is some content. But reproduced when you are trying insert text into last editor line (no delimiter).
![screenshot from 2017-02-06 14-44-30](https://cloud.githubusercontent.com/assets/24434676/22650358/30a87d28-ec7f-11e6-8db2-b39faaf838df.png)

**Comment by mlabuda** [comment]
PR #1602
