### ISSUE TITLE
DebuggerTest is failing due to timeout exception

### ISSUE THREAD

**Issue by apodhrad** [jboss-reddeer/reddeer#1645]
**Error Message**

Timeout after: 60 s.: The following jobs are still running:
 Creating maven-archetype-quickstart

**Stacktrace**

org.jboss.reddeer.common.exception.WaitTimeoutExpiredException: Timeout after: 60 s.: The following jobs are still running:
	Creating maven-archetype-quickstart

**Comment by apodhrad** [comment]
It seems that the creating a maven project takes too long.

**Comment by rawagner** [comment]
PR is here https://github.com/jboss-reddeer/reddeer/pull/1656
