### ISSUE TITLE
testMixedRequirementsSuite failed 

### ISSUE THREAD

**Issue by rawagner** [jboss-reddeer/reddeer#1666]
see https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/reddeer.prcheck/238/jdk=jdk1.8,label=rhel7/testReport/org.jboss.reddeer.junit.test.runner/RedDeerSuiteTest/testMixedRequirementsSuite/

**Comment by odockal** [comment]
Seems that branch was not rebased and so, the fix is not there yet... @theJNOVAK can you please rebase your [branch](https://github.com/theJNOVAK/reddeer/tree/core-tests) and push it again?Thanks!

**Comment by theJNOVAK** [comment]
Rebased and pushed.

**Comment by rawagner** [comment]
seems to be ok :)
