### ISSUE TITLE
Review and update missing javadoc for org.jboss.reddeer.swt plugin

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#468]
Review and update missing javadoc

all public members (classes, methods, etc.) should contains javadoc
user should be able able to understand behaviour from description without analyzing the code
use since (for example since 0.5 means <0.5-snapshot...0.6)
use deprecated with referencing the replacement

**Comment by jpeterka** [comment]
@mmalina no postpones anymore!

**Comment by mmalina** [comment]
The last open task #692 was just merged now, so closing this as well.
