### ISSUE TITLE
Review and update missing javadoc for org.jboss.reddeer.workbench plugin

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#471]
Review and update missing javadoc

all public members (classes, methods, etc.) should contains javadoc
user should be able able to understand behaviour from description without analyzing the code
use since (for example since 0.5 means <0.5-snapshot...0.6)
use deprecated with referencing the replacement

**Comment by ldimaggi** [comment]
It seems to be there now:

http://machydra.brq.redhat.com:8080/job/RedDeer_master_javadoc/ws/target/site/apidocs/org/jboss/reddeer/workbench/api/package-summary.html

Is something else needed here?

**Comment by mlabuda** [comment]
Well, there are plenty of classes in workbench plugin which do not contain any javadoc and that is missing. You have to go through each class and for each public method create javadoc.

**Comment by ldimaggi** [comment]
Marian - can you tell me what is missing?

The source tree for Workbench is:

tree
.
── org
    └── jboss
        └── reddeer
            └── workbench
                ├── Activator.java
                ├── api
                │   ├── Editor.java
                │   ├── package-info.java
                │   ├── View.java
                │   └── WorkbenchPart.java
                ├── condition
                │   ├── ContentAssistantShellIsOpened.java
                │   ├── EditorHasValidationMarkers.java
                │   ├── EditorWithTitleIsActive.java
                │   └── package-info.java
                ├── exception
                │   └── WorkbenchLayerException.java
                ├── handler
                │   ├── EditorHandler.java
                │   └── package-info.java
                ├── impl
                │   ├── editor
                │   │   ├── AbstractEditor.java
                │   │   ├── DefaultEditor.java
                │   │   ├── Marker.java
                │   │   ├── package-info.java
                │   │   └── TextEditor.java
                │   ├── shell
                │   │   └── WorkbenchShell.java
                │   └── view
                │       ├── AbstractView.java
                │       └── WorkbenchView.java
                └── preference
                    └── WorkbenchPreferencePage.java

And the javadocs are:

org/jboss/reddeer/workbench/
org/jboss/reddeer/workbench/Activator.html
org/jboss/reddeer/workbench/package-frame.html
org/jboss/reddeer/workbench/package-summary.html
org/jboss/reddeer/workbench/package-tree.html
org/jboss/reddeer/workbench/package-use.html
org/jboss/reddeer/workbench/api/
org/jboss/reddeer/workbench/api/Editor.html
org/jboss/reddeer/workbench/api/View.html
org/jboss/reddeer/workbench/api/WorkbenchPart.html
org/jboss/reddeer/workbench/api/package-frame.html
org/jboss/reddeer/workbench/api/package-summary.html
org/jboss/reddeer/workbench/api/package-tree.html
org/jboss/reddeer/workbench/api/package-use.html
org/jboss/reddeer/workbench/api/class-use/
org/jboss/reddeer/workbench/api/class-use/Editor.html
org/jboss/reddeer/workbench/api/class-use/View.html
org/jboss/reddeer/workbench/api/class-use/WorkbenchPart.html
org/jboss/reddeer/workbench/class-use/
org/jboss/reddeer/workbench/class-use/Activator.html
org/jboss/reddeer/workbench/condition/
org/jboss/reddeer/workbench/condition/ContentAssistantShellIsOpened.html
org/jboss/reddeer/workbench/condition/EditorHasValidationMarkers.html
org/jboss/reddeer/workbench/condition/EditorWithTitleIsActive.html
org/jboss/reddeer/workbench/condition/package-frame.html
org/jboss/reddeer/workbench/condition/package-summary.html
org/jboss/reddeer/workbench/condition/package-tree.html
org/jboss/reddeer/workbench/condition/package-use.html
org/jboss/reddeer/workbench/condition/class-use/
org/jboss/reddeer/workbench/condition/class-use/ContentAssistantShellIsOpened.html
org/jboss/reddeer/workbench/condition/class-use/EditorHasValidationMarkers.html
org/jboss/reddeer/workbench/condition/class-use/EditorWithTitleIsActive.html
org/jboss/reddeer/workbench/exception/
org/jboss/reddeer/workbench/exception/WorkbenchLayerException.html
org/jboss/reddeer/workbench/exception/package-frame.html
org/jboss/reddeer/workbench/exception/package-summary.html
org/jboss/reddeer/workbench/exception/package-tree.html
org/jboss/reddeer/workbench/exception/package-use.html
org/jboss/reddeer/workbench/exception/class-use/
org/jboss/reddeer/workbench/exception/class-use/WorkbenchLayerException.html
org/jboss/reddeer/workbench/handler/
org/jboss/reddeer/workbench/handler/EditorHandler.html
org/jboss/reddeer/workbench/handler/package-frame.html
org/jboss/reddeer/workbench/handler/package-summary.html
org/jboss/reddeer/workbench/handler/package-tree.html
org/jboss/reddeer/workbench/handler/package-use.html
org/jboss/reddeer/workbench/handler/class-use/
org/jboss/reddeer/workbench/handler/class-use/EditorHandler.html
org/jboss/reddeer/workbench/impl/
org/jboss/reddeer/workbench/impl/editor/
org/jboss/reddeer/workbench/impl/editor/AbstractEditor.html
org/jboss/reddeer/workbench/impl/editor/DefaultEditor.html
org/jboss/reddeer/workbench/impl/editor/Marker.html
org/jboss/reddeer/workbench/impl/editor/TextEditor.html
org/jboss/reddeer/workbench/impl/editor/package-frame.html
org/jboss/reddeer/workbench/impl/editor/package-summary.html
org/jboss/reddeer/workbench/impl/editor/package-tree.html
org/jboss/reddeer/workbench/impl/editor/package-use.html
org/jboss/reddeer/workbench/impl/editor/class-use/
org/jboss/reddeer/workbench/impl/editor/class-use/AbstractEditor.html
org/jboss/reddeer/workbench/impl/editor/class-use/DefaultEditor.html
org/jboss/reddeer/workbench/impl/editor/class-use/Marker.html
org/jboss/reddeer/workbench/impl/editor/class-use/TextEditor.html
org/jboss/reddeer/workbench/impl/shell/
org/jboss/reddeer/workbench/impl/shell/WorkbenchShell.html
org/jboss/reddeer/workbench/impl/shell/package-frame.html
org/jboss/reddeer/workbench/impl/shell/package-summary.html
org/jboss/reddeer/workbench/impl/shell/package-tree.html
org/jboss/reddeer/workbench/impl/shell/package-use.html
org/jboss/reddeer/workbench/impl/shell/class-use/
org/jboss/reddeer/workbench/impl/shell/class-use/WorkbenchShell.html
org/jboss/reddeer/workbench/impl/view/
org/jboss/reddeer/workbench/impl/view/AbstractView.html
org/jboss/reddeer/workbench/impl/view/WorkbenchView.html
org/jboss/reddeer/workbench/impl/view/package-frame.html
org/jboss/reddeer/workbench/impl/view/package-summary.html
org/jboss/reddeer/workbench/impl/view/package-tree.html
org/jboss/reddeer/workbench/impl/view/package-use.html
org/jboss/reddeer/workbench/impl/view/class-use/
org/jboss/reddeer/workbench/impl/view/class-use/AbstractView.html
org/jboss/reddeer/workbench/impl/view/class-use/WorkbenchView.html
org/jboss/reddeer/workbench/preference/
org/jboss/reddeer/workbench/preference/TestingPreferencePage.TestCategory.html
org/jboss/reddeer/workbench/preference/TestingPreferencePage.TestTopCategory.html
org/jboss/reddeer/workbench/preference/TestingPreferencePage.html
org/jboss/reddeer/workbench/preference/WorkbenchPreferenceDialogTest.html
org/jboss/reddeer/workbench/preference/WorkbenchPreferencePage.html
org/jboss/reddeer/workbench/preference/package-frame.html
org/jboss/reddeer/workbench/preference/package-summary.html
org/jboss/reddeer/workbench/preference/package-tree.html
org/jboss/reddeer/workbench/preference/package-use.html
org/jboss/reddeer/workbench/preference/class-use/
org/jboss/reddeer/workbench/preference/class-use/TestingPreferencePage.TestCategory.html
org/jboss/reddeer/workbench/preference/class-use/TestingPreferencePage.TestTopCategory.html
org/jboss/reddeer/workbench/preference/class-use/TestingPreferencePage.html
org/jboss/reddeer/workbench/preference/class-use/WorkbenchPreferenceDialogTest.html
org/jboss/reddeer/workbench/preference/class-use/WorkbenchPreferencePage.html
org/jboss/reddeer/workbench/test/
org/jboss/reddeer/workbench/test/Activator.html
org/jboss/reddeer/workbench/test/package-frame.html
org/jboss/reddeer/workbench/test/package-summary.html
org/jboss/reddeer/workbench/test/package-tree.html
org/jboss/reddeer/workbench/test/package-use.html
org/jboss/reddeer/workbench/test/class-use/
org/jboss/reddeer/workbench/test/class-use/Activator.html
org/jboss/reddeer/workbench/test/editor/
org/jboss/reddeer/workbench/test/editor/EditorTest.html
org/jboss/reddeer/workbench/test/editor/TextEditorTest.html
org/jboss/reddeer/workbench/test/editor/package-frame.html
org/jboss/reddeer/workbench/test/editor/package-summary.html
org/jboss/reddeer/workbench/test/editor/package-tree.html
org/jboss/reddeer/workbench/test/editor/package-use.html
org/jboss/reddeer/workbench/test/editor/class-use/
org/jboss/reddeer/workbench/test/editor/class-use/EditorTest.html
org/jboss/reddeer/workbench/test/editor/class-use/TextEditorTest.html
org/jboss/reddeer/workbench/test/ui/
org/jboss/reddeer/workbench/test/ui/editor/
org/jboss/reddeer/workbench/test/ui/editor/SimpleEditor.html
org/jboss/reddeer/workbench/test/ui/editor/package-frame.html
org/jboss/reddeer/workbench/test/ui/editor/package-summary.html
org/jboss/reddeer/workbench/test/ui/editor/package-tree.html
org/jboss/reddeer/workbench/test/ui/editor/package-use.html
org/jboss/reddeer/workbench/test/ui/editor/class-use/
org/jboss/reddeer/workbench/test/ui/editor/class-use/SimpleEditor.html
org/jboss/reddeer/workbench/test/ui/views/
org/jboss/reddeer/workbench/test/ui/views/LabelView.html
org/jboss/reddeer/workbench/test/ui/views/package-frame.html
org/jboss/reddeer/workbench/test/ui/views/package-summary.html
org/jboss/reddeer/workbench/test/ui/views/package-tree.html
org/jboss/reddeer/workbench/test/ui/views/package-use.html
org/jboss/reddeer/workbench/test/ui/views/class-use/
org/jboss/reddeer/workbench/test/ui/views/class-use/LabelView.html
org/jboss/reddeer/workbench/test/view/
org/jboss/reddeer/workbench/test/view/ViewTest.html
org/jboss/reddeer/workbench/test/view/package-frame.html
org/jboss/reddeer/workbench/test/view/package-summary.html
org/jboss/reddeer/workbench/test/view/package-tree.html
org/jboss/reddeer/workbench/test/view/package-use.html
org/jboss/reddeer/workbench/test/view/class-use/
org/jboss/reddeer/workbench/test/view/class-use/ViewTest.html
org/jboss/reddeer/workbench/test/view/impl/
org/jboss/reddeer/workbench/test/view/impl/WorkbenchViewTest.html
org/jboss/reddeer/workbench/test/view/impl/package-frame.html
org/jboss/reddeer/workbench/test/view/impl/package-summary.html
org/jboss/reddeer/workbench/test/view/impl/package-tree.html
org/jboss/reddeer/workbench/test/view/impl/package-use.html
org/jboss/reddeer/workbench/test/view/impl/class-use/
org/jboss/reddeer/workbench/test/view/impl/class-use/WorkbenchViewTest.html

**Comment by ldimaggi** [comment]
The problem is that the existing javadoc is not reviewed and there could be for example just author and not sufficient description of class/enum/interface/method. So it's more likely review and filling gaps of javadoc.

The issue that you want to see addressed is not simply the Javadoc, but the QUALITY of the information in the Javadoc

For which classes do we not want Javadocs? Why would we not want Javadocs for all classes?

Private inner classes could be wasteful to have javadoc, if their name is enough self-explanatory
e.g. having a SWT shell with cancel button in class name ShellWithCancelButton would not provide much more information, but it also depends on preferences of programmer, but otherwise, every public class has to have javadoc. And others (protected, private) could have but it's not required.
