### ISSUE TITLE
Wizard for RedDeer custom schema requirements

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#609]
Goal is to improve creating custom requirements. Wizard should be able:
* define basic parameters of custom schema
* generate xsd schema, generate example xml schema
* generate needed classes and test template

No need to have it in 0.6 so proper design first and have it properly implemented until RedDeer 1.0 is available.

**Comment by mlabuda** [comment]
We decided to not implement this feature.
