### ISSUE TITLE
rhopp_User Guide - Update Editor page for latest updates (markers, etc.)

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#694]

**Comment by rhopp** [comment]
I've read through that page and made some changes (mainly in first section, which had some obsolete info in it).
[DIFF](https://github.com/jboss-reddeer/reddeer/wiki/Editors/_compare/61fd88a05b4d903b84d239d469f5e11e89aa43f8...82a28fcf61967f9e58aa59a56f834c361c6da86e?diff=unified&short_path=342b3c0#diff-342b3c0942dd2822a0cc7759f306893c)
