### ISSUE TITLE
Support for multiple ways howto achive given operation

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#770]
This is more a long term problem probably to be addressed somewhere between 1.x-2.x
Thing is it would be good to support operations by multiple ways, basically
- by UI simulation (org.eclipse.swt API should be involved) 
- by Eclipse API call (org.eclipse.direct API should be involved)

Also there are scenarios when tester wants to invoke operation by mouse or by keyboard, by context menu or by top level menu or workbench toolitem. Currently we don't care how it is done in our implementations. 

User should be able to choose which one he want's to use without changing a code much

**Comment by mlabuda** [comment]
We already have direct plugin next to UI manipulation.
