### ISSUE TITLE
Newly created launcher doesn't contain VM arguments

### ISSUE THREAD

**Issue by apodhrad** [jboss-reddeer/reddeer#801]
Newly created launcher should contain the following VM argument

-Xms256m -Xmx512m -XX:PermSize=256m -XX:MaxPermSize=384m -Dusage_reporting_enabled=false

**Comment by jpeterka** [comment]
-Dusage_reporting_enabled=false is JBT specific, should not be part of RedDeer. Other setting is valid.

**Comment by ljelinkova** [comment]
Duplicates https://github.com/jboss-reddeer/reddeer/issues/952
