### ISSUE TITLE
Seeing a new issue -  view.open() failing with an error that open method must be run

### ISSUE THREAD

**Issue by ldimaggi** [jboss-reddeer/reddeer#943]
This error started showing up recently - should views continue to extend WorkbenchView?

        MylynBuildView view = new MylynBuildView();
        view.open();   <-------- This statement fails with the following exception:

org.jboss.reddeer.workbench.exception.WorkbenchLayerException: Cannot perform the specified operation before initialization provided by open method
    at org.jboss.reddeer.workbench.impl.view.AbstractView.viewPartIsNotNull(AbstractView.java:278)
    at org.jboss.reddeer.workbench.impl.view.AbstractView.activate(AbstractView.java:118)
    at org.jboss.reddeer.workbench.impl.view.AbstractView.maximize(AbstractView.java:83)
    at org.jboss.tools.mylyn.ui.bot.test.MylynTestJenkins.testServer(MylynTestJenkins.java:69)

**Comment by ljelinkova** [comment]
It seems that for some reason the view is open but not found when it should be activated by direct call (not UI). I've created an issue to provide more debug information for such cases https://github.com/jboss-reddeer/reddeer/issues/947

**Comment by ljelinkova** [comment]
This is probably the same issue logged agains Eclipse Marse https://bugs.eclipse.org/bugs/show_bug.cgi?id=459479

Please note that Red Deer is currently tested and ran against Eclipse Luna

**Comment by ljelinkova** [comment]
This issue should be fixed by https://github.com/jboss-reddeer/reddeer/pull/955. If not, please reopen this issue.
