### ISSUE TITLE
RedDeer Test launcher is created without any VM args in JBDS

### ISSUE THREAD

**Issue by apodhrad** [jboss-reddeer/reddeer#952]
RedDeer Test launcher is created without any VM args in JBDS.

1. Install RedDeer into JBDS 8.0.2
2. Run > Run Configurations...
3. Select RedDeer Test and create new launcher
4. Select tab Arguments and see VM arguments (VM args is empty)

Or you can select any RedDeer test a run it as RedDeer test, the create launcher has no VM args.
Without correct VM args the tests cannot by run properly (usually OutOfMemory occurs).

**Comment by apodhrad** [comment]
@ljelinkova could you have a look at #933 whether it is somehow related, please?

**Comment by ljelinkova** [comment]
This is not a RD bug, but PDE behaviour. It happens for all installations that do not use default "eclipse" launchher and "eclipse.ini" configuration (includint JBDS and RD product). 

It is caused byt this code in AbstractBundleContainer.getVMArguments() when loading the VM arguments - the names are hardcoded to eclipse and eclipse.ini. One workaroud is to rename the launcher and ini file to eclipse and eclipse.ini

```
Manipulator manipulator = fwAdmin.getManipulator();
ConfigData configData = new ConfigData(null, null, null, null);

String home = getLocation(true);
manipulator.getLauncherData().setLauncher(new File(home, "eclipse")); //$NON-NLS-1$
File installDirectory = new File(home);
if (Platform.getOS().equals(Platform.OS_MACOSX))
		installDirectory = new File(installDirectory, "Eclipse.app/Contents/MacOS"); //$NON-NLS-1$
manipulator.getLauncherData().setLauncherConfigLocation(new File(installDirectory, "eclipse.ini")); 
}//$NON-NLS-1$
```

**Comment by rawagner** [comment]
Shouldn't we create a bug in upstream then ?
