### ISSUE TITLE
Deprecate swt,jface,workbench,uiforms and create rcp plugin

### ISSUE THREAD

**Issue by rawagner** [jboss-reddeer/reddeer#964]
- decision to merge workbench, swt, jface, uiforms into one plugin RCP
- org.jboss.reddeer.rcp.swt, org.jboss.reddeer.rcp.jface... 
- marked as deprecated in 0.8, removed in 1.0

**Comment by jpeterka** [comment]
This was already overruled by creating core plugin and additional re-factoring.
