### ISSUE TITLE
Release RedDeer 0.7 tasks

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#973]
Steps:
Change to 0.7
Tag 0.7
Build stable update site
Change to 0.8-snapshot

**Comment by mmalina** [comment]
PR for release is here: #974

**Comment by mmalina** [comment]
The 0.7.0 build was promoted here:
http://download.jboss.org/jbosstools/updates/stable/luna/core/reddeer/0.7.0/

**Comment by mmalina** [comment]
PR for update to 0.8.0-SNAPSHOT: #975

**Comment by mmalina** [comment]
Right now one thing is missing: The archetype is in the staging repo of JBoss Nexus repository, but we need to release it.

**Comment by mmalina** [comment]
Note for next time: To avoid maven preferring older snapshot builds rather then the release (0.7.0.201410241320 > 0.7.0) we will use a Final qualifier. So the command to move the version will be something like:
mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=0.8.0.Final

**Comment by jpeterka** [comment]
Closing this one as 0.7 was released and all major tasks were done.

**Comment by mmalina** [comment]
BTW, the archetype is now released also:
https://origin-repository.jboss.org/nexus/content/repositories/releases/org/jboss/reddeer/jboss-reddeer-archetype/
And here are the instructions on how to release it:
https://developer.jboss.org/docs/DOC-52892

**Comment by mmalina** [comment]
Update site zip is attached to the release in GitHub: https://github.com/jboss-reddeer/reddeer/releases/tag/v0.7.0
