### ISSUE TITLE
Combine several plugins into org.jboss.reddeer.rcp

### ISSUE THREAD

**Issue by jpeterka** [jboss-reddeer/reddeer#976]
Based on our decisions we should combine swt,workbench,uiforms into one rcp plugin:
I'm still doubting if we have really serious reasons for such a huge re-factoring and that's why I think it ok to raise one last round of discussion before doing it.
Based on our previous discussion it was like we have really serious reasons but after some more time and thinking I'm still not sure if the reasons for that are really so strong.

Major points for re-factoring:
1) No possible cross dependencies
- currently there are no "dangerous" cross RedDeer dependencies as I can see  (maybe I've missed something, if so please comment). Do we expect this problem with some future API? There are dependencies from rd.swt to eclipse.ui which are not "nice" but we can live with them. 

2) It would be clear where to locate API
- specifically can be quite confusing to know where API is placed and where to place API (uiforms, workbench) and references can be quite strange. But again, it's probably not critical.

3) We decided not to support plain SWT application. That's good decision IMO but does it really strongly support this re-factoring?

4) It will be somehow clear to have strong RCP part and Eclipse part of RedDeer. Users either needs RCP or Eclipse. This is probably the best argument together with potential cross-referencing I see.  

5) I don't remember anything else, please add if you do.

Updated:
After more and more thinking about my final conclusion is that this task  is unfortunately only covering architecture violations and finding reasons for doing that. And it's not right approach. Re-factoring is ok if it's done for good reasons. This is not one of them IMHO. Reasons might be strong but are not good. I think we should keep slowly working on cleaning swt plugin to make the architecture better and less monolithic and break swt plugin down rather then create one big plugin to cover all these internal violations. So I have not much problem with huge refactoring but rather with this monolithic way. 

Please put your comments below to support pros and cons and what you think is better. 
@rawagner @ljelinkova @mlabuda @vpakan @apodhrad

**Comment by vpakan** [comment]
I agree with cleaning SWT plugin instead of merging plugins to one big plugin. At least for users it would be harmless

**Comment by mlabuda** [comment]
I think we talked that there is no big difference between SWT and Workbench plugins and at first we wanted merge just those two together but after further discussion we decided to add more plugins (uiforms, maybe others?) to this one superplugin. Do I recall it correctly?

**Comment by rawagner** [comment]
I always thought that the architecture we created was based on the premise that each plugin represents some supported layer of user's GUI app. (SWT, SWT+JFace and so on). However now we know that we wont support all these layers. So to not break this premise we should merge all mentioned plugins into lowest supported layer which is rcp.


If we keep those plugins separated than what is an actual use case to use only let's say SWT plugin and not whole RCP plugin stack when only RCP layer is supported ?

**Comment by ljelinkova** [comment]
I think we all agree that the SWT plugin should not contain any references to other, "higher level" plugins. We tried to clenup SWT plugin several times and we came into conclusion we actually cannot get rid of Workbench dependency withou compromising functionality. For me, the architecture would be much more cleaner if we created one RCP plugin. 

The other thing is, of course, that it will break user's code and it will require a lot of effort. However, Red Deer is just 0.8 version and I really wish we could release 1.0 with the pride it is the best we could do. And the best means clear architecture. I suppose we might get some users involved after 1.0 if we bacome Eclipse project and it will be too late to refactor then. 

So, I vote for big refactoring to make 1.0 release really cool.

**Comment by vpakan** [comment]
* SWT layer is all you need to test any e4 rcp application e.g. swt app running on Eclipse platform but in many case without any needs for workbench. When building RedDeer enhancements for particular app SWT layer should be minimum dependency user should need.
* logically and historically it should be one separate plugin
* removing cycle dependencies by merging plugins together seems wrong either we have  wrong architecture or we should created third plugin with functionality we are not able to extract from workbench and swt plugins
* even it's just v. 0.8.0 refactorring is bad

I suggest to discuss it deeply on next RedDeer meeting to make final decision

So I'm against merging

**Comment by ljelinkova** [comment]
@vpakan I agree to discuss it further but I suggest you have a look at SWT plugin and propose some solution how to get rid of workbench dependency. It is used in the widget lookup to be able to narrow the search for a specified view or editor and so far nobody has found good solution.

**Comment by jpeterka** [comment]
Thanks for your comments, based on today's meeting issue will be resolved by adding core plugin with appropriate functionality, more to see https://drive.google.com/file/d/0B6amrFzJyMGUQ1BILTg1akh2QWs/view?usp=sharing
