### ISSUE TITLE
Add Red Deer archetype to Central

### ISSUE THREAD

**Issue by mlabuda** [jboss-reddeer/reddeer#978]

**Comment by psrna** [comment]
What should I do? @mlabuda  can you please clarify?

**Comment by mlabuda** [comment]
@rawagner I think we talked about this and now I do not remember quite clear what this was about. Do you remember?

**Comment by rawagner** [comment]
@psrna @mlabuda  we need to publish reddeer maven archetype to maven central repository. Im not sure what the process looks like but jboss examples/quickstarts are published to maven central repository too so it would be a good idea to contact team which is working on those examples

**Comment by jpeterka** [comment]
@psrna status ?

**Comment by psrna** [comment]
I've opened a ticket for it.
https://engineering.redhat.com/rt/Ticket/Display.html?id=361550

**Comment by psrna** [comment]
The ticket is resolved now. Closing.
