### ISSUE TITLE
Create basic RedDeer screencasts

### ISSUE THREAD

**Issue by mlabuda** [jboss-reddeer/reddeer#979]
Screencast topics:
- Getting started - Install, create plug-in, create simple test and execute
- RedDeer Spy
- RedDeer Generator
- RedDeer Recorder
- RedDeer Log Parser

**Comment by mlabuda** [comment]
#987 will fulfill this. This one closing as duplicate.

**Comment by jpeterka** [comment]
This would be first stage during 0.8, everyone creates one screencast and best makers will do a production version for 1.0
